apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: scion-deployment
spec:
  selector:
    matchLabels:
      app: scion-scope
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: scion-scope
    spec:
      containers:
        - name: scion-scope
          image: mshow1980/today-webapp: 44  # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: scion-ssvc
spec:
  selector:
    app: scion-scope
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 9376 # The port exposed by the service
  type: NodePort # type of the service.